CREATE TABLE IF NOT EXISTS "db_schema" ("key" VARCHAR(64) NOT NULL PRIMARY KEY, "value" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "admin_key" ("key" TEXT NOT NULL PRIMARY KEY, "valid" INTEGER NOT NULL, "key_used" INTEGER NOT NULL, "cookie" TEXT NOT NULL, "create_time" INTEGER NOT NULL);
CREATE INDEX "admin_key_cookie" ON "admin_key" ("cookie");
CREATE TABLE IF NOT EXISTS "user" ("qqid" INTEGER NOT NULL PRIMARY KEY, "nickname" TEXT, "authority_group" INTEGER NOT NULL, "privacy" INTEGER NOT NULL, "clan_group_id" INTEGER, "last_login_time" INTEGER NOT NULL, "last_login_ipaddr" INTEGER NOT NULL, "password" CHAR(64), "must_change_password" INTEGER NOT NULL, "notify_preference" INTEGER NOT NULL, "login_code" CHAR(6), "login_code_available" INTEGER NOT NULL, "login_code_expire_time" INTEGER NOT NULL, "salt" VARCHAR(16) NOT NULL, "deleted" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "user_login" ("qqid" INTEGER NOT NULL, "auth_cookie" CHAR(64) NOT NULL, "auth_cookie_expire_time" INTEGER NOT NULL, "last_login_time" INTEGER NOT NULL, "last_login_ipaddr" INTEGER NOT NULL, PRIMARY KEY ("qqid", "auth_cookie"));
CREATE TABLE IF NOT EXISTS "clan_group" ("group_id" INTEGER NOT NULL PRIMARY KEY, "group_name" TEXT, "privacy" INTEGER NOT NULL, "game_server" VARCHAR(2) NOT NULL, "notification" INTEGER NOT NULL, "level_4" INTEGER NOT NULL, "battle_id" INTEGER NOT NULL, "apikey" VARCHAR(16) NOT NULL, "boss_cycle" INTEGER NOT NULL, "boss_num" INTEGER NOT NULL, "boss_health" INTEGER NOT NULL, "challenging_member_qq_id" INTEGER, "boss_lock_type" INTEGER NOT NULL, "challenging_start_time" INTEGER NOT NULL, "challenging_comment" TEXT, "deleted" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "clan_member" ("group_id" INTEGER NOT NULL, "qqid" INTEGER NOT NULL, "role" INTEGER NOT NULL, "last_save_slot" INTEGER, "remaining_status" TEXT, PRIMARY KEY ("group_id", "qqid"));
CREATE INDEX "clan_member_group_id" ON "clan_member" ("group_id");
CREATE INDEX "clan_member_qqid" ON "clan_member" ("qqid");
CREATE TABLE IF NOT EXISTS "clan_challenge" ("cid" INTEGER NOT NULL PRIMARY KEY, "bid" INTEGER NOT NULL, "gid" INTEGER NOT NULL, "qqid" INTEGER NOT NULL, "challenge_pcrdate" INTEGER NOT NULL, "challenge_pcrtime" INTEGER NOT NULL, "boss_cycle" INTEGER NOT NULL, "boss_num" INTEGER NOT NULL, "boss_health_ramain" INTEGER NOT NULL, "challenge_damage" INTEGER NOT NULL, "is_continue" INTEGER NOT NULL, "message" TEXT, "behalf" INTEGER);
CREATE INDEX "clan_challenge_qqid" ON "clan_challenge" ("qqid");
CREATE INDEX "clan_challenge_bid_gid" ON "clan_challenge" ("bid", "gid");
CREATE INDEX "clan_challenge_qqid_challenge_pcrdate" ON "clan_challenge" ("qqid", "challenge_pcrdate");
CREATE INDEX "clan_challenge_bid_gid_challenge_pcrdate" ON "clan_challenge" ("bid", "gid", "challenge_pcrdate");
CREATE TABLE IF NOT EXISTS "character" ("chid" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(64) NOT NULL, "frequent" INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS "user_box" ("qqid" INTEGER NOT NULL, "chid" INTEGER NOT NULL, "last_use" INTEGER NOT NULL, "rank" INTEGER NOT NULL, "stars" INTEGER NOT NULL, "equit" INTEGER NOT NULL, PRIMARY KEY ("qqid", "chid"));
CREATE TABLE IF NOT EXISTS "clan_subscribe" ("sid" INTEGER NOT NULL PRIMARY KEY, "gid" INTEGER NOT NULL, "qqid" INTEGER NOT NULL, "subscribe_item" INTEGER NOT NULL, "message" TEXT, "created_time" INTEGER NOT NULL);
CREATE INDEX "clan_subscribe_gid" ON "clan_subscribe" ("gid");
CREATE INDEX "clan_subscribe_gid_qqid_subscribe_item" ON "clan_subscribe" ("gid", "qqid", "subscribe_item");
